# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: newpool

variables:
- group: pi-shaped-group
steps:

- task: CmdLine@2
  inputs:
    script: |
      sudo docker build -t pishapeddevacr01.azurecr.io/backend:$(Build.BuildNumber) -f src/backend/Dockerfile src/backend/
      sudo docker build -t pishapeddevacr01.azurecr.io/frontend:$(Build.BuildNumber) -f src/frontend/Dockerfile src/frontend/
  displayname: Build Docker Images
- task: CmdLine@2
  inputs:
    script: |
      trivy fs . --scanners vuln,secret,config --severity CRITICAL --exit-code 0
      trivy image pishapeddevacr01.azurecr.io/frontend:$(Build.BuildNumber) --severity CRITICAL --scanners vuln --exit-code 0
      trivy image pishapeddevacr01.azurecr.io/backend:$(Build.BuildNumber) --severity CRITICAL --scanners vuln --exit-code 0
  displayname: Trivy scan
- task: CmdLine@2
  inputs:
    script: |
      sudo docker login https://pishapeddevacr01.azurecr.io -u $(user) -p $(password)
      sudo docker push pishapeddevacr01.azurecr.io/frontend:$(Build.BuildNumber)
      sudo docker push pishapeddevacr01.azurecr.io/backend:$(Build.BuildNumber)
  displayname: Push Docker Images