# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: newpool

variables:
- group: pi-shaped-group
- name: image-tag
  value: $(Date:yyyyMMdd).$(Rev:r)
steps:

- task: CmdLine@2
  inputs:
    script: |
      sudo docker login https://pishapeddevacr01.azurecr.io -u $(user) -p $(password)
      sudo docker build -t pishapeddevacr01.azurecr.io/backend:$(image-tag) -f src/backend/Dockerfile src/backend/
      sudo docker push pishapeddevacr01.azurecr.io/backend:$(image-tag)
      sudo docker build -t pishapeddevacr01.azurecr.io/frontend:$(image-tag) -f src/frontend/Dockerfile src/frontend/
      sudo docker push pishapeddevacr01.azurecr.io/frontend:$(image-tag)
  