# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: newpool

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'pishapeddevacr01'
    command: 'login'
- task: CmdLine@2
  inputs:
    script: |
      
      sudo docker build -t pishapeddevacr01.azurecr.io/backend:latest -f src/backend/Dockerfile src/backend/
      sudo docker push pishapeddevacr01.azurecr.io/backend:latest
      sudo docker build -t pishapeddevacr01.azurecr.io/frontend:latest -f src/frontend/Dockerfile src/frontend/
      sudo docker push pishapeddevacr01.azurecr.io/frontend:latest